### ISSUE TITLE
Type Definition causes issues with Module Resolution NodeNext

### ISSUE THREAD

**Issue by OfficialCRUGG** [haruaki07/phosphor-svelte#15]
While using the icon components itself works, VSCode shows an error when trying to use any of the components when `moduleResolution` is set to `NodeNext` in the tsconfig:
![image](https://github.com/haruaki07/phosphor-svelte/assets/25248999/c2aa8757-4f0b-4d39-89bf-db08c8c3ed75)

According to a Svelte Maintainer, this is caused by the usage of `./shared` instead of `./shared.js` in the type definitions:
![image](https://github.com/haruaki07/phosphor-svelte/assets/25248999/9c6d6078-d2f8-47f1-ba5e-76da24254556)

**Comment by OfficialCRUGG** [comment]
It's important to note that this might need additional testing. As far as I know, this shouldn't break anything though.

**Comment by OfficialCRUGG** [comment]
Any update on this? The issue still persists, and on my end, the PR I submitted solves this.

**Comment by haruaki07** [comment]
> Any update on this? The issue still persists, and on my end, the PR I submitted solves this.

Please review the suggested changes on the PR. I apologize for the delay. I mistakenly forgot to mark it as suggest changes, so it remained in a pending state.
