### ISSUE TITLE
Wrong packaging?

### ISSUE THREAD

**Issue by akiarostami** [haruaki07/phosphor-svelte#3]
Recently when I run a couple of sveltekit projects with phosphor-svelte, I get these messages:

`phosphor-svelte is incorrectly packaged. Please contact the package author to fix.` (sveltekit v1.0.0-next.202)

and

`phosphor-svelte doesn't appear to be written in CJS, but also doesn't appear to be a valid ES module (i.e. it doesn't have "type": "module" or an .mjs extension for the entry point). Please contact the package author to fix.` (sveltekit v1.0.0-next.210)

I didn't get these message with earlier version of sveltekit / vite.

**Comment by haruaki07** [comment]
Fixed in [v1.1.2](https://github.com/haruaki07/phosphor-svelte/releases/tag/v1.1.2). Thanks!
