### ISSUE TITLE
Phosphor has released more icons since your last update

### ISSUE THREAD

**Issue by hitaboy** [haruaki07/phosphor-svelte#8]
Hi there,

Phosphor has released more icons since your last update here. You do have any plans to update phosphor-svelte?

Thanks!

**Comment by haruaki07** [comment]
Hello, my apologies for being late to respond.

Yes, if any new icons are released, I will make sure to update them regularly. 
If you wish to contribute, please feel free to submit a PR.

**Comment by hitaboy** [comment]
Hi @haruaki07, I want to contrinute to this repo, updating it with the last icons. 
I cloned the repo and tried to build it but I got this error:
[Error: ENOENT: no such file or directory, scandir '/Users/<my-user>/Documents/<project-folder>/phosphor-svelte/core/assets']
I guess that I have to put all the phosphor icons there or something similar. 
Could you guide me a little bit? Please.
If I learn the process I will take care of the updates. 
Thanks in advance !!!

**Comment by haruaki07** [comment]
Hello @hitaboy, 
Its look like the phosphor-icons/core submodule hasn't been cloned yet. You can try run the following command first:
```shell
git submodule update --init --recursive
``` 
Then run build again. 
I hope this will help you.

**Comment by hitaboy** [comment]
Thank you !
I will try to pull request if any day I see that it is not up to date.
